#!/usr/bin/env bash
# scripts/bob-attribution.sh
#
# Generates docs/bob-evidence/ATTRIBUTION.md from the repository itself.
#
# Why this exists. A judge can verify a dated, counted claim and cannot verify
# "Bob helped a lot". Every number below is computed from the tracked tree or
# from git at run time, so the table is falsifiable: re-run this and it either
# reproduces or the repository changed.
#
# It also prints what the evidence does NOT establish. A tool that only
# generates the flattering half is a marketing script.
#
# Usage:
#   scripts/bob-attribution.sh           regenerate the document
#   scripts/bob-attribution.sh --check   fail if the document is stale (CI)

set -euo pipefail
cd "$(dirname "$0")/.."

OUT="docs/bob-evidence/ATTRIBUTION.md"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# --- computed facts, none hardcoded -----------------------------------------
BOB_FILES=$(git ls-files .bob | wc -l | tr -d ' ')
MODES=$(grep -cE '^  - slug:' .bob/custom_modes.yaml)
SCOPES=$(grep -cE '^\s+- fileRegex:' .bob/custom_modes.yaml)
SKILLS=$(git ls-files '.bob/skills/*/SKILL.md' | wc -l | tr -d ' ')
RULES=$(git ls-files '.bob/rules-*/AGENTS.md' | wc -l | tr -d ' ')
EVIDENCE=$(git ls-files docs/bob-evidence | wc -l | tr -d ' ')
# Deliberately NOT recording the total commit count. Committing this document
# changes it, so the document would invalidate itself on its own commit and
# --check would fail forever. The meaningful number is the trailer count.
TRAILERS=$(git log --grep='Tool: IBM-Bob' --oneline | wc -l | tr -d ' ')
MCP_TOOLS=$(python3 -c "import json;print(len(json.load(open('.bob/mcp.json'))['mcpServers']['manifest-eval']['alwaysAllow']))")

# A shallow clone cannot resolve the lane SHAs, and would silently emit
# "UNRESOLVED" into the table, which then fails --check as a confusing diff
# instead of naming the real cause. Both jobs in eval-gate.yml set
# fetch-depth: 0; this fails loudly if that ever regresses.
if [ -f .git/shallow ]; then
  echo "FAIL: shallow clone. The lane-enforcement SHAs cannot be resolved," >&2
  echo "      so this table would be generated wrong. Use fetch-depth: 0." >&2
  exit 1
fi

# The two commits where a write-scoped mode's regex governed one path.
LANE_A=e6788e5
LANE_B=377a146
lane_line() { git log -1 --format='%h, %ad, %an' --date=short "$1" 2>/dev/null || echo "$1, UNRESOLVED"; }

TMP=$(mktemp)
{
  echo "# IBM Bob attribution, generated"
  echo
  echo "Generated by \`scripts/bob-attribution.sh\` from the tracked tree and from git."
  echo "Do not hand-edit. Re-run the script instead, and CI asserts it is current."
  echo
  echo "## What is committed and countable"
  echo
  echo "| Evidence | Count | Where |"
  echo "|---|---|---|"
  echo "| Tracked files under \`.bob/\` | $BOB_FILES | \`.bob/\` |"
  echo "| Custom modes | $MODES | \`.bob/custom_modes.yaml\` |"
  echo "| fileRegex write scopes | $SCOPES | \`.bob/custom_modes.yaml\` |"
  echo "| Regime skills | $SKILLS | \`.bob/skills/*/SKILL.md\` |"
  echo "| Mode rule files | $RULES | \`.bob/rules-*/AGENTS.md\` |"
  echo "| Eval tools exposed to Bob over MCP | $MCP_TOOLS | \`.bob/mcp.json\` |"
  echo "| Files in the evidence folder | $EVIDENCE | \`docs/bob-evidence/\` |"
  echo
  echo "## The write scopes, verbatim from the shipped yaml"
  echo
  echo '```'
  paste -d' ' <(grep -E '^  - slug:' .bob/custom_modes.yaml | sed 's/.*slug: *//') \
              <(grep -E '^\s+- fileRegex:' .bob/custom_modes.yaml | sed 's/.*fileRegex: *//') \
    | awk '{printf "%-20s %s\n", $1, substr($0, index($0,$2))}'
  echo '```'
  echo
  echo "A mode refuses a write outside its regex in the editor, before a bad"
  echo "write exists. That is a different guarantee from catching it in review."
  echo
  echo "## The lane enforcement actually happening, with dates"
  echo
  echo "| Commit, date, author | What it shows |"
  echo "|---|---|"
  echo "| $(lane_line $LANE_A) | \`docs/architecture.svg\` written under the evidence scope, refused by the frontend scope |"
  echo "| $(lane_line $LANE_B) | the same path, second write, same scope boundary |"
  echo
  echo "Asserted by \`tests/test_bob_lane_enforcement.py\`, which checks the shipped"
  echo "regex table rather than a pasted transcript."
  echo
  echo "## What this evidence does NOT establish"
  echo
  echo "Stated plainly, because a table that only reports the flattering half is"
  echo "marketing rather than evidence."
  echo
  echo "1. **No per-commit Bob authorship trailer exists.** Commits carrying a"
  echo "   \`Tool: IBM-Bob\` trailer: **$TRAILERS**. The team did not record one while"
  echo "   building, so nothing here proves which lines Bob wrote, and no such trailer"
  echo "   will be added after the fact: back-stamping the history would manufacture"
  echo "   the evidence rather than report it."
  echo "2. **A committed mode proves the constraint, not the usage.** \`.bob/\` shows the"
  echo "   write scopes a session ran under. It does not measure how much work Bob did."
  echo "3. **The Bobalytics screenshots are the spend record**, and they are subscription"
  echo "   totals, not per-file attribution."
  echo "4. **The Plan-mode session was never captured.** \`docs/bob-evidence/plan-mode-critical-path.md\`"
  echo "   records that absence rather than reconstructing a transcript."
} > "$TMP"

if [ "$CHECK" = "1" ]; then
  if ! diff -q "$TMP" "$OUT" >/dev/null 2>&1; then
    echo "FAIL: $OUT is stale. Run scripts/bob-attribution.sh" >&2
    diff "$OUT" "$TMP" >&2 || true
    rm -f "$TMP"; exit 1
  fi
  rm -f "$TMP"; echo "OK: $OUT is current."; exit 0
fi

mv "$TMP" "$OUT"
echo "Wrote $OUT"
echo "  .bob files=$BOB_FILES modes=$MODES scopes=$SCOPES skills=$SKILLS rules=$RULES"
echo "  Tool: IBM-Bob trailers=$TRAILERS (reported, not manufactured)"
