// engine/interlocks/__tests__/deorbit-compliance.test.ts
// Tests for the FCC 5-year deorbit compliance interlock.
//
// The decay table (data/decay-table.json) is the fixture -- generated by
// pipeline/decay.py and committed. Tests verify the interlock logic and
// the project differentiator: solar cycle changes the compliance verdict.

import { describe, it, expect } from 'vitest';
import { computeDeorbitCompliance } from '../deorbit-compliance';

// ---------------------------------------------------------------------------
// Above-threshold orbit
// ---------------------------------------------------------------------------

describe('computeDeorbitCompliance: above 2000 km threshold', () => {
  it('returns ABSTAIN for orbit above 2000 km', () => {
    const result = computeDeorbitCompliance(2100, 180);
    expect(result.verdict).toBe('ABSTAIN');
    expect(result.aboveRuleThreshold).toBe(true);
  });

  it('exactly 2001 km is still above threshold', () => {
    const result = computeDeorbitCompliance(2001, 180);
    expect(result.verdict).toBe('ABSTAIN');
  });

  it('exactly 2000 km is NOT above threshold (boundary)', () => {
    const result = computeDeorbitCompliance(2000, 180);
    expect(result.aboveRuleThreshold).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Low-altitude compliant orbits (should be OK at nominal F10.7)
// ---------------------------------------------------------------------------

describe('computeDeorbitCompliance: 400 km orbit', () => {
  it('400 km with Bc=180 is compliant (OK) at nominal F10.7', () => {
    const result = computeDeorbitCompliance(400, 180);
    expect(result.verdict).toBe('OK');
    expect(result.lifetimeYears).toBeLessThanOrEqual(5.0);
  });

  it('FCC limit is 5 years', () => {
    const result = computeDeorbitCompliance(400, 180);
    expect(result.fccLimitYears).toBe(5);
  });
});

// ---------------------------------------------------------------------------
// The differentiator: 550 km orbit compliance depends on solar cycle
// ---------------------------------------------------------------------------

describe('computeDeorbitCompliance: differentiator at 550 km', () => {
  it('550 km Bc=180 with nominal F10.7=120 is non-compliant (VIOLATED or AT_RISK)', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(['VIOLATED', 'AT_RISK']).toContain(result.verdict);
    expect(result.lifetimeYears).toBeGreaterThan(5.0);
  });

  it('550 km Bc=180 at solar max (F10.7=200) is compliant (OK)', () => {
    const result = computeDeorbitCompliance(550, 180, 200);
    expect(result.verdict).toBe('OK');
    expect(result.lifetimeYears).toBeLessThanOrEqual(5.0);
  });

  it('550 km Bc=180 at solar min (F10.7=70) is non-compliant (VIOLATED)', () => {
    const result = computeDeorbitCompliance(550, 180, 70);
    expect(result.verdict).toBe('VIOLATED');
    expect(result.lifetimeYears).toBeGreaterThan(5.0);
  });

  it('lifetimeYearsLow > lifetimeYears > lifetimeYearsHigh (solar min = longest lifetime)', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(result.lifetimeYearsLow).toBeGreaterThanOrEqual(result.lifetimeYears);
    expect(result.lifetimeYears).toBeGreaterThanOrEqual(result.lifetimeYearsHigh);
  });
});

// ---------------------------------------------------------------------------
// F10.7 override interpolation
// ---------------------------------------------------------------------------

describe('computeDeorbitCompliance: F10.7 override', () => {
  it('override equal to table nominal returns same lifetime', () => {
    const noOverride = computeDeorbitCompliance(550, 180);
    const withOverride = computeDeorbitCompliance(550, 180, noOverride.f107Assumed);
    expect(withOverride.lifetimeYears).toBe(noOverride.lifetimeYears);
  });

  it('override F10.7 is stored on the result', () => {
    const result = computeDeorbitCompliance(400, 180, 150);
    expect(result.f107Assumed).toBe(150);
  });

  it('high F10.7 override yields shorter lifetime than low override', () => {
    const highSolar = computeDeorbitCompliance(550, 180, 200);
    const lowSolar = computeDeorbitCompliance(550, 180, 70);
    expect(highSolar.lifetimeYears).toBeLessThan(lowSolar.lifetimeYears);
  });
});

// ---------------------------------------------------------------------------
// Output contract
// ---------------------------------------------------------------------------

describe('computeDeorbitCompliance: output contract', () => {
  it('citation cfrTitle is 47', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(result.citation.cfrTitle).toBe(47);
  });

  it('citation section is 25.283', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(result.citation.section).toBe('25.283');
  });

  it('method string is present and non-empty', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(result.method.length).toBeGreaterThan(0);
  });

  it('tableEntryNotFound is false for a valid orbit', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(result.tableEntryNotFound).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Nearest-altitude lookup
// ---------------------------------------------------------------------------

describe('computeDeorbitCompliance: nearest-altitude lookup', () => {
  it('exact altitude 550 sets closestAltitudeKmUsed to null', () => {
    const result = computeDeorbitCompliance(550, 180);
    expect(result.closestAltitudeKmUsed).toBeNull();
  });

  it('off-table altitude 530 uses nearest table entry', () => {
    const result = computeDeorbitCompliance(530, 180);
    // A non-exact lookup must report the closest altitude used
    const tableAlts = [400, 450, 500, 550, 600, 650, 700];
    const closest = result.closestAltitudeKmUsed;
    expect(closest).not.toBeNull();
    expect(tableAlts).toContain(closest);
  });

  // Beyond the grid entirely, not merely between two rows. /mission accepts any
  // positive perigee, and the table stops at 700 km, so an 850 km orbit still
  // returns a legal verdict computed from the 700 km row. That substitution is
  // 150 km wide and it decides a compliance outcome, so it must be reported
  // rather than folded silently into the number.
  //
  // Found by running a rival's defect class back at us: a project publishing
  // location predictions from a training set holding twelve Arctic coordinates.
  // The question is not whether the model is good, it is whether the range a
  // user will actually enter is inside the data the model saw.
  it('an orbit ABOVE the table ceiling reports the substitution it made', () => {
    const result = computeDeorbitCompliance(850, 180);
    expect(result.closestAltitudeKmUsed).toBe(700);
    expect(result.lifetimeYears).toBeGreaterThan(0);
  });

  it('a ballistic coefficient outside the tiers still reports its altitude row', () => {
    // BC tiers are 120 / 180 / 250. 400 is far above all three.
    const result = computeDeorbitCompliance(530, 400);
    expect(result.closestAltitudeKmUsed).not.toBeNull();
  });
});

describe('the row disclosure explains itself in the payload', () => {
  // The old field is correct and unreadable: null means "exact grid hit", a
  // rule that lived only in a code comment. A judge reading the JSON saw null
  // beside a real VIOLATED verdict and could not tell an exact match from a
  // failed lookup. These assert the payload no longer requires that knowledge.

  it('an EXACT grid point still names the row it used', () => {
    const r = computeDeorbitCompliance(550, 180);
    expect(r.verdict).toBe('VIOLATED');
    expect(r.closestAltitudeKmUsed).toBeNull(); // unchanged, exact means null
    expect(r.altitudeKmUsed).toBe(550);
    expect(r.altitudeMatch).toBe('exact');
  });

  it('an off-grid orbit says the row was substituted, and which', () => {
    const r = computeDeorbitCompliance(523, 180);
    expect(r.altitudeKmUsed).not.toBeNull();
    expect(r.altitudeMatch).toBe('nearest-row-substituted');
    expect(r.closestAltitudeKmUsed).toBe(r.altitudeKmUsed);
  });

  it('above the rule threshold, no row was used and it says so', () => {
    const r = computeDeorbitCompliance(2500, 180);
    expect(r.verdict).toBe('ABSTAIN');
    expect(r.altitudeKmUsed).toBeNull();
    expect(r.altitudeMatch).toBe('no-row-used');
  });

  it('a real verdict is NEVER reported without naming its row', () => {
    // The invariant the whole fix exists for.
    for (const alt of [400, 450, 500, 523, 550, 600, 650, 700]) {
      const r = computeDeorbitCompliance(alt, 180);
      if (r.verdict === 'ABSTAIN') continue;
      expect(r.altitudeKmUsed, `altitude ${alt} produced a verdict with no row`).not.toBeNull();
      expect(['exact', 'nearest-row-substituted']).toContain(r.altitudeMatch);
    }
  });
});
